version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: fightclub
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: api
    restart: unless-stopped
    env_file:
      - .env.server
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: web
    restart: unless-stopped
    env_file:
      - .env.client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo_data:
